spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: pre013
    password: ${DB_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 991088085016-3udvngkchprg1opii9jvhbagp64bpqhh.apps.googleusercontent.com
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: ${ADMIN_ADDRESS}
config:
  domain: http://pre-13.s3-website.ap-northeast-2.amazonaws.com:80
