spring:
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  config:
    activate:
      on-profile: production
    import: 'aws-parameterstore:'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${RDS_PASSWORD}
    url: jdbc:mysql://database.czloyqya09hy.ap-northeast-2.rds.amazonaws.com/mydb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: ${GOOGLE_CLIENT_ID}
            clientSecret: ${GOOGLE_CLIENT_SECRET}
            scope: profile,email
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: arubu3667@gmail.com
config:
  domain: http://fe-pre013.s3-website.ap-northeast-2.amazonaws.com
aws:
  paramstore:
    enabled: true
    prefix: /spring-boot-aws
    profile-separator: _
    name: seb44-pre013
