spring:
  jpa:
    hibernate:
      ddl-auto: create  # (1) 스키마 자동 생성
    show-sql: true      # (2) SQL 쿼리 출력
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 12345678
    url: jdbc:mysql://database.czloyqya09hy.ap-northeast-2.rds.amazonaws.com/mydb?useSSL=false&characterEncoding=UTF-8&serverTimezone=UTC
    username: admin
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 991088085016-3udvngkchprg1opii9jvhbagp64bpqhh.apps.googleusercontent.com
            clientSecret: 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
            scope: profile,email
logging:
  level:
    org:
      springframework:
        orm:
          jpa: DEBUG
server:
  servlet:
    encoding:
      force-response: true
jwt:
  key: kevin12341234123412341234123412341111111111111111111111111111111111111111111111111111111111
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420
mail:
  address:
    admin: arubu3667@gmail.com
config:
  domain: http://fe-pre013.s3-website.ap-northeast-2.amazonaws.com
