version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Build Starting on `date`
      - cd server
      - chmod +x ./gradlew
      - ./gradlew build
  post_build:
    commands:
      - echo $(basename ./server/build/libs/*.jar)
      - sed -i 's/${JWT_SECRET_KEY}/$JWT_SECRET_KEY/' /path/to/server/src/main/resources/application.yml
      - sed -i 's/${RDS_PASSWORD}/$RDS_PASSWORD/' /path/to/server/src/main/resources/application.yml
      - sed -i 's/${RDS_URL}/$RDS_URL/' /path/to/server/src/main/resources/application.yml
      - sed -i 's/${GOOGLE_CLIENT_SECRET}/$GOOGLE_CLIENT_SECRET/' /path/to/server/src/main/resources/application.yml
      - sed -i 's/${CONFIG_DOMAIN}/$CONFIG_DOMAIN/' /path/to/server/src/main/resources/application.yml
      - sed -i 's/${ADDRESS_ADMIN}/$ADDRESS_ADMIN/' /path/to/server/src/main/resources/application.yml
artifacts:
  files:
    - server/build/libs/*.jar
    - server/scripts/**
    - server/appspec.yml
    - server/src/main/resources/application.yml
  discard-paths: yes